const BASE_URL = import.meta.env.VITE_BASE_URL || "http://localhost:5000";
const BACKEND_API_ROUTES = {
    LOGIN: '/superadmin/login',
    GET_TOKEN_VALIDITY: '/member/token',
    GET_SUPERADMIN: '/superadmin',
    GET_SUPERADMIN_BY_ID: '/superadmin/:id',
    CREATE_SUPERADMIN: '/superadmin/create',
    GET_MEMBER: '/member',
    GET_TOTAL_MEMBER:'/member/total',
    GET_TOTAL_MEMBER_BY_DEPARTMENT:'/member/department/total',
    GET_MEMBER_BY_ID: '/member/:id',
    CREATE_MEMBER: '/member/create',
    GET_MEETING:'/meeting',
    GET_TOTAL_MEETING:'/meeting/total',
    GET_TOTAL_TEAM_BUILDING:'/meeting/total/teamBuildings',
    GET_TOTAL_EVENT:'/meeting/total/events',
    GET_TOTAL_DEPARTMENT_MEETING:'/meeting/total/departmentMeetings',
    GET_TOTAL_GENERAL_ASSEMBLY:'/meeting/total/generalAssemblys',
    GET_EVENT: '/meeting/event',
    GET_TEAM_BUILDING: '/meeting/teamBuilding',
    GET_DEPARTMENT_MEETING: '/meeting/departmentMeeting',
    GET_GENERAL_ASSEMBLY: '/meeting/generalAssembly',
    GET_MEETING_BY_ID:'/meeting/by-id/:id',
    CREATE_MEETING:'/meeting/create',
    UPDATE_MEETING: '/meeting/',
    JOIN_MEETING:'/meeting/join',
    GET_MEETINGQUESTION:'/meetingquestion',
    GET_MEETINGQUESTION_BY_ID: '/meetingquestion/meeting/:id',
    GET_MEETING_PRESENT_LIST: '/meeting/:type/present-members/:id',
    CREATE_MEETINGQUESTION:'/meetingquestion/create',
    ANSWER_MEETINGQUESTION:'/meetingquestion/answer',
    GET_INTERVIEW:'/interview',
    GET_INTERVIEW_BY_ID:'/interview/interview/:id',
    GET_RECENT_INTERVIEW: '/interview/recent',
    GET_FINISHED_INTERVIEW: '/interview/finished',
    CREATE_INTERVIEW:'/interview/createInterview',
    UPDATE_INTERVIEW: '/interview/update/',
    GET_CANDIDAT:'/candidat',
    CREATE_CANDIDAT:'/candidat/create',
    UPGRADE_CANDIDAT:'/candidat/upgrade',
    UPDATE_CANDIDAT:'/candidat/update/',
    CREATE_SECTION:'/sections',
    MODIFY_SECTION:'/sections/:id',
    DELETE_SECTION:'/sections/:id',
    CREATE_INTERVIEWQUESTION:'/interviewquestion/create',
    MODIFY_INTERVIEWQUESTION:'/interviewquestion/update/:id',
    DELETE_INTERVIEWQUESTION:'/interviewquestion/delete/:id',
    GET_INTERVIEW_Sections:'/sections/interview/:id',
    GET_EVALUATION_TABLE : '/matrix',
    UPDATE_EVALUATION_TABLE: '/matrix'
};

export { BASE_URL, BACKEND_API_ROUTES };