const BASE_URL = import.meta.env.VITE_BASE_URL || "http://localhost:5000";
const BACKEND_API_ROUTES = {
    LOGIN: '/superadmin/login',
    GET_TOKEN_VALIDITY: '/member/token',
    GET_SUPERADMIN: '/superadmin',
    GET_SUPERADMIN_BY_ID: '/superadmin/:id',
    CREATE_SUPERADMIN: '/superadmin/create',
    GET_MEMBER: '/member',
    GET_TOTAL_MEMBER:'/member/total',
    GET_MEMBER_BY_ID: '/member/:id',
    CREATE_MEMBER: '/member/create',
    GET_MEETING:'/meeting',
    GET_TOTAL_MEETING:'/meeting/total',
    GET_TOTAL_TEAM_BUILDING:'/meeting/total/teamBuildings',
    GET_TOTAL_EVENT:'/meeting/total/events',
    GET_TOTAL_DEPARTMENT_MEETING:'/meeting/total/departmentMeetings',
    GET_TOTAL_GENERAL_ASSEMBLY:'/meeting/total/generalAssemblys',
    GET_EVENT: '/meeting/event',
    GET_TEAM_BUILDING: '/meeting/teamBuilding',
    GET_DEPARTMENT_MEETING: '/meeting/departmentMeeting',
    GET_GENERAL_ASSEMBLY: '/meeting/generalAssembly',
    GET_MEETING_BY_ID:'/meeting/:id',
    CREATE_MEETING:'/meeting/create',
    JOIN_MEETING:'/meeting/join',
    GET_MEETINGQUESTION:'/meetingquestion',
    CREATE_MEETINGQUESTION:'/meetingquestion/create',
    ANSWER_MEETINGQUESTION:'/meetingquestion/answer',
    GET_INTERVIEW:'/interview',
    GET_RECENT_INTERVIEW: '/interview/recent',
    GET_FINISHED_INTERVIEW: '/interview/finished',
    CREATE_INTERVIEW:'/interview/createInterview',
    UPDATE_INTERVIEW: '/interview/update/',
    GET_INTERVIEWQUESTION:'/interviewquestion',
    CREATE_INTERVIEWQUESTION:'/interviewquestion/create',
    GET_CANDIDAT:'/candidat',
    CREATE_CANDIDAT:'/candidat/create',
    UPGRADE_CANDIDAT:'/candidat/upgrade',
    CREATE_SECTION:'/section/create',
};

export { BASE_URL, BACKEND_API_ROUTES };